# This workflow will publish a package to npm using OIDC trusted publisher
# For more information see: https://docs.npmjs.com/generating-provenance-statements

name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Publish to npm
        run: npm publish --provenance --access public
